import type { Evidence } from "./evidence";
import { validateEvidence } from "./evidence-validation";
import type { IsoDateTime, VerificationResultId } from "./ids";
import type { SuccessCriterion } from "./success-criterion";
import { validateSuccessCriterion } from "./success-criterion-validation";
import type { Task } from "./task";
import { validateTask } from "./task-validation";
import type { CriterionVerification, VerificationOutcome, VerificationResult } from "./verification-result";
import { validateVerificationResult } from "./verification-result-validation";
export interface VerificationEngineInput { task: Task; criteria: SuccessCriterion[]; aiOutput: string; evidence: Evidence[]; resultId: VerificationResultId; verifiedAt: IsoDateTime; }
export type VerificationEngineErrorCode = "INVALID_INPUT" | "INVALID_RESULT";
export class VerificationEngineError extends Error { constructor(public readonly code: VerificationEngineErrorCode, message: string) { super(message); this.name = "VerificationEngineError"; } }
const PASS_ASSERTION = "[DONECHECK:PASS]"; const FAIL_ASSERTION = "[DONECHECK:FAIL]";
function assertionOutcome(evidence: Evidence): VerificationOutcome | undefined { if (evidence.source !== "system" || !["log", "test_report"].includes(evidence.kind)) return undefined; const content = evidence.content.trim().toUpperCase(); if (content.startsWith(FAIL_ASSERTION)) return "fail"; if (content.startsWith(PASS_ASSERTION)) return "pass"; return undefined; }
function evaluateCriterion(criterion: SuccessCriterion, evidence: Evidence[]): CriterionVerification { const evidenceIds = [...new Set(evidence.map((item) => item.id))]; if (criterion.kind === "subjective") return { criterionId: criterion.id, outcome: "inconclusive", reason: "Subjective criteria require human judgment; automated verification cannot manufacture a pass.", evidenceIds }; if (evidence.length === 0) return { criterionId: criterion.id, outcome: "inconclusive", reason: "No criterion-scoped evidence was provided.", evidenceIds }; const assertions = evidence.map(assertionOutcome).filter(Boolean) as VerificationOutcome[]; if (assertions.includes("fail")) return { criterionId: criterion.id, outcome: "fail", reason: "System evidence contains an explicit DoneCheck FAIL assertion.", evidenceIds }; if (assertions.includes("pass")) return { criterionId: criterion.id, outcome: "pass", reason: "System evidence contains an explicit DoneCheck PASS assertion.", evidenceIds }; return { criterionId: criterion.id, outcome: "inconclusive", reason: "Evidence is present but contains no machine-verifiable DoneCheck PASS or FAIL assertion.", evidenceIds }; }
function requireValidInput(input: VerificationEngineInput): void { if (!validateTask(input.task).valid) throw new VerificationEngineError("INVALID_INPUT", "Task failed runtime validation."); if (!Array.isArray(input.criteria) || input.criteria.length === 0) throw new VerificationEngineError("INVALID_INPUT", "At least one success criterion is required."); if (input.criteria.some((criterion) => !validateSuccessCriterion(criterion).valid)) throw new VerificationEngineError("INVALID_INPUT", "One or more success criteria failed runtime validation."); if (typeof input.aiOutput !== "string" || input.aiOutput.trim().length === 0) throw new VerificationEngineError("INVALID_INPUT", "AI-generated output must be a non-empty string."); if (!Array.isArray(input.evidence) || input.evidence.some((item) => !validateEvidence(item).valid)) throw new VerificationEngineError("INVALID_INPUT", "One or more evidence items failed runtime validation."); }
export function verifyTask(input: VerificationEngineInput): VerificationResult { requireValidInput(input); const structuralIssues: string[] = []; const criterionById = new Map<string, SuccessCriterion>(); for (const criterion of input.criteria) { if (criterionById.has(criterion.id)) { structuralIssues.push(`duplicate criterionId: ${criterion.id}`); continue; } criterionById.set(criterion.id, criterion); if (criterion.taskId !== input.task.id) structuralIssues.push(`criterion ${criterion.id} belongs to another task`); } const evidenceIds = new Set<string>(); const evidenceByCriterion = new Map<string, Evidence[]>(); for (const item of input.evidence) { if (evidenceIds.has(item.id)) structuralIssues.push(`duplicate evidenceId: ${item.id}`); evidenceIds.add(item.id); if (item.taskId !== input.task.id) structuralIssues.push(`evidence ${item.id} belongs to another task`); if (item.criterionId && !criterionById.has(item.criterionId)) { structuralIssues.push(`evidence ${item.id} references unknown criterion ${item.criterionId}`); continue; } if (item.criterionId) { const scoped = evidenceByCriterion.get(item.criterionId) ?? []; scoped.push(item); evidenceByCriterion.set(item.criterionId, scoped); } } const criteria = [...criterionById.values()].map((criterion) => evaluateCriterion(criterion, evidenceByCriterion.get(criterion.id) ?? [])); const requiredIds = new Set([...criterionById.values()].filter((criterion) => criterion.required).map((criterion) => criterion.id)); const requiredResults = criteria.filter((criterion) => requiredIds.has(criterion.criterionId)); let outcome: VerificationOutcome; let reason: string; if (structuralIssues.length > 0) { outcome = "fail"; reason = `Verification failed closed: ${structuralIssues.join("; ")}`; } else if (requiredResults.length === 0) { outcome = "inconclusive"; reason = "No required criteria are defined; an automatic pass is not permitted."; } else if (requiredResults.some((criterion) => criterion.outcome === "fail")) { outcome = "fail"; reason = "One or more required criteria failed."; } else if (requiredResults.some((criterion) => criterion.outcome === "inconclusive")) { outcome = "inconclusive"; reason = "At least one required criterion is inconclusive."; } else { outcome = "pass"; reason = "All required criteria passed."; } const result: VerificationResult = { id: input.resultId, taskId: input.task.id, outcome, reason, criteria, verifiedAt: input.verifiedAt }; const validated = validateVerificationResult(result); if (!validated.valid) throw new VerificationEngineError("INVALID_RESULT", "Engine output failed VerificationResult validation."); return validated.result; }
